#pragma once
#include <iostream>
#include <algorithm>
#include <conio.h>
#include <iomanip>
#include <vector>
#include <sstream>
#include <string>
#include <fstream>
#include <filesystem>
#include <Windows.h>
#include "Utilities.h"
#include "InputValidator.h"
#include "Person.h"
#include "PeopleManager.h"
#include "Location.h"
#include "LocationManager.h"
#include "ClassContainer.h"
#include "Menu.h"

